### ISSUE TITLE
Nostr

### ISSUE THREAD

**Issue by alltheseas** [MicroStrategy/did-btc-spec#7]
Just in case your engineering and research team overlooked - [nostr](https://github.com/nostr-protocol) exists. 

Unlike decentralized in name only solutions such as [ATProto](https://atproto.com/), Nostr has the highest ratio of active devs to active users. There is no corporation behind nostr. It is a protocol, just at Bitcoin is a protocol. 

[Nostr](https://fiatjaf.com/nostr.html) just works.

Nostr takes the cryptographic keypair portion of PGP, BTC, and via opt-in [NIPs](https://github.com/nostr-protocol/nips/) enables bottoms up experimentation not possible since the early days of the internet. 

Not using nostr is your decision to make.

Not referencing one of the few DIDs that "just work" in nostr in your proposed DID spec makes your proposal look like unfinished homework.

**Comment by mikestaub** [comment]
We already have https://github.com/TBD54566975/did-nostr which makes different tradeoffs than DID:btc. The whole point of the DID spec was to allow arbitrary methods for different use cases.

**Comment by LeoBeb** [comment]
Hello @alltheseas ,
we are well aware of nostr's existence. We did some research into integrating did:btc into a custom nostr client, to allow for a Bitcoin-anchored nsec.
That can potentially solve one of nostr's main inconveniences: key rotation. If the nostr identity is tied to an identifier instead of a public key, a user can create a new keypair and update the DID with it. Older notes signed with the previous key can still be validated by comparing the timestamps they were created with the ones from the Bitcoin blockchain.

**Comment by melvincarvalho** [comment]
For your information, there is a community group for Nostr at the W3C. While it is not particularly active at the moment, it may still be a useful place to discuss standardization efforts.

You can find more details here: [W3C Nostr Community Group](https://www.w3.org/community/nostr/).

**Comment by LeoBeb** [comment]
@melvincarvalho ,
 thanks a lot for your input. We will reach that out if we continue working on a nostr integration.

**Comment by alltheseas** [comment]
>  one of nostr's main inconveniences: key rotation

What is the job-to-be-done, user story, user benefits for the technical solution of 'key rotation' for mstr?

**Comment by LeoBeb** [comment]
> What is the job-to-be-done, user story, user benefits for the technical solution of 'key rotation' for mstr?

The did:btc method already provides a function to update a DID and rotate the associated public key https://microstrategy.github.io/did-btc-spec/#update

Key rotation is still an open discussion in the Nostr protocol: https://github.com/nostr-protocol/nostr/issues/45

We think a potential integration of Nostr with did:btc, or any other DID method that allows for key rotation, can allow Nostr users to recover lost accounts to some degree. However, MSTR is not actively pursuing such integration at the moment.

**Comment by melvincarvalho** [comment]
Quick update, since this came up in the discussion:

did:nostr has now reached v0.1.0 and has been published by the W3C Nostr Community Group as a Community Group Draft Report:

https://nostrcg.github.io/did-nostr/

It gives Nostr keys a direct DID representation using secp256k1 / BIP-340 keys, with Multikey verification methods, conformance test vectors, and resolver support. The did:nostr ecosystem now has 30+ implementations:

https://did-nostr.com/

This is directly relevant to the Nostr / key-rotation discussion above: did:nostr provides the native Nostr-facing DID method for existing Nostr keys, with resolver interoperability, including a DIF did-resolver driver for the Universal Resolver, and a path to Web/VC integration via Data Integrity.

It may be worth referencing did:nostr in the Nostr integration or related work section.
